### ISSUE TITLE
error speed up

### ISSUE THREAD

**Issue by foxhacker0000** [psyk3r/psybot#2]
command:
python self.py

error:
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
Traceback (most recent call last):
  File "F:\messengers\let\scripts\self\psybot\self.py", line 6, in <module>
    bot = Client(
          ^^^^^^^
TypeError: Client.__init__() got an unexpected keyword argument 'session_name'

**Comment by psyk3r** [comment]
It seems like you forgot to install the required libraries from "requirements.txt" file. The current version you are using is deprecated and will be updated in a few weeks and you also have to set your credentials in the "self.py" file in the new version in order to make it work.
